apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-simple-rest-deployment
  labels:
    app: nodejs-simple-rest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs-simple-rest
  template:
    metadata:
      labels:
        app: nodejs-simple-rest
    spec:
      containers:
      - name: nodejs-simple-rest
        image: cloudmahesh/nodejs-simple-rest:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-simple-rest-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: nodejs-simple-rest